version: "3"
services:
  send-tweet-with-media:
    image: luisalejandro/send-tweet-with-media:latest
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /home/luisalejandro/app
    volumes:
      - .:/home/luisalejandro/app
    env_file:
      - .env